name: Go CI
on:
  - push
  - pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1
      - run: go test ./...
      # Testing with -update enabled isn't intended to update the golden files, but to help validate that there aren't
      # problems when updating is enabled, race conditions in the update process etc
      # Tests are run multiple times to help expose race-conditions as they aren't always reproduced on a single run
      - run: go test -race -count 5 ./... -update -clean
      - run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
      - name: Upload code coverage
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.txt
