name: Go CI
on:
  - push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1
      - run: go test ./...
      # Testing with -update enabled isn't intended to update the golden files, but to help validate that there aren't
      # problems when updating is enabled, race conditions in the update process etc
      - run: go test -race ./... -update
      - run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
      - name: Upload code coverage
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.txt
